import type { Metadata } from "next";
import { Geist, Geist_Mono, DM_Serif_Display, Inter } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const dmSerifDisplay = DM_Serif_Display({
  variable: "--font-dm-serif-display",
  subsets: ["latin"],
  weight: "400",
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Fair Field - Living in Harmony",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
          {/*Google Tag Manager*/}
          <script
                      dangerouslySetInnerHTML={{
                          __html: `(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
    new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
    j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
    'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
    })(window,document,'script','dataLayer','GTM-WRJ9R4VB');`,
                      }}
          />
          {/*End Google Tag Manager*/}

          {/* Meta Pixel Code */}
          <script
                dangerouslySetInnerHTML={{
                    __html: `!function(f,b,e,v,n,t,s)
                            {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
                            n.callMethod.apply(n,arguments):n.queue.push(arguments)};
                            if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
                            n.queue=[];t=b.createElement(e);t.async=!0;
                            t.src=v;s=b.getElementsByTagName(e)[0];
                            s.parentNode.insertBefore(t,s)}(window, document,'script',
                            'https://connect.facebook.net/en_US/fbevents.js');
                            fbq('init', '1739365096653458');
                            fbq('track', 'PageView');`,
                }}
          />
          <script 
                dangerouslySetInnerHTML={{
                    __html: `
                      // Trigger the custom event for phone call click
                      window.addEventListener("load", (event) => {
                        // Trigger the custom event for booking a visit
                        document.querySelector('.book-visit-button').addEventListener('click', function() {
                          fbq('track', 'CompleteRegistration', {
                            content_name: 'Exclusive Site Visit',
                            content_type: 'service',
                            value: 0,  // You can update this value if there's a monetary cost for booking
                            currency: 'INR', // Replace with your currency if needed
                            action: 'Book Visit'
                          });
                        });

                        // Trigger the custom event for phone call click
                        document.querySelector('.call-us-button').addEventListener('click', function() {
                          fbq('track', 'Contact', {
                            content_name: 'Call Us',
                            content_type: 'contact',
                            action: 'Phone Call Clicked',
                            value: 0,  // No direct monetary value, but you can update if needed
                            currency: 'INR' // Replace with your currency
                          });
                        });
                      });
                    `
                }} 
          />
          <script 
                dangerouslySetInnerHTML={{
                    __html: `
                      <noscript>
                        <img height="1" width="1" style="display:none" src="https://www.facebook.com/tr?id=1739365096653458&ev=PageView&noscript=1" />
                      </noscript>
                    `
                }} 
          />
          {/* End Meta Pixel Code */}
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${dmSerifDisplay.variable} ${inter.variable} antialiased`}
      >
        {/*Google Tag Manager*/}
        <div dangerouslySetInnerHTML={{
              __html: `
                <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-WRJ9R4VB"
                height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
              `
            }} 
        />
        {/*End Google Tag Manager*/}
        {children}
      </body>
    </html>
  );
}
